---
title: "Adventures of a Technical Writer Manager"
date: 2020-11-23
---

title: Caley Burton
author: People Manager, Technical Writer
email: caleyburton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Check out my repos, my code and documentation contributions, and my love for open source projects.

# social links
twitter_username: caleycaley
github_username:  kidlovesindie

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
